name: 'imdb_analytics'
version: '1.0'
config-version: 2

profile: 'default'

target-path: 'target'
clean-targets:
  - 'target'
  - 'dbt_modules'

model-paths: ['models']
analysis-paths: ["analyses"]
test-paths: ['tests']
macro-paths: ['macros']
snapshot-paths: ['snapshots']

models:
  imdb_analytics:
    +materialized: view
